apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zt6jkp3zr-python
  janus-idp.io/tekton: zt6jkp3zr-python
  backstage.io/kubernetes-id: zt6jkp3zr-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zt6jkp3zr-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
